name: problm-solver
channels:
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - tqdm
  - poethepoet
  - llama-cpp-python>=0.3.23
  - pandas
  - fsspec
  - huggingface_hub
  - uv
  - pip
  - pip:
    - .
