site_name: probLM-solver
site_description: A python library built on top of llama.cpp which generates and performs statistical analysis on language model outputs.
site_url: https://muse-writes.github.io/probLM-solver
repo_url: https://github.com/muse-writes/probLM-solver
repo_name: muse-writes/probLM-solver

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
